from searches.A_Star_Search import AStarSearch
from searches.Iterative_Depth_Search import IterativeDepthSearch
from searches.Breadth_Search import BreadthSearch
from searches.Depth_Search import DepthSearch
